### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "stack" is null

### ISSUE THREAD

**Issue by fellock** [Globox1997/TooltipRareness#6]
Hi,

I encountered this bug while interacting with Patchouli books and when messing with the menus.
I found similar crashes online and the issue seems to be related to this mod - possibly something to do with the mixins.

My logs:
https://pastebin.com/raw/qiVcmKnF
https://pastebin.com/raw/vyL8rJ4S

Similar logs:
https://pastebin.com/raw/vir8gc0i
https://pastebin.com/raw/YB80Dv4v

Possibly related logs
https://pastebin.com/raw/dsxEx5ug
https://pastebin.com/raw/Tq9da7BE

cheers,
filok

**Comment by Globox1997** [comment]
Fixed with itsmiirs pr

**Comment by Konglomneshued** [comment]
Still having the issue, and I don't know what itsmiirs pr is, so I don't understand how I fix it.

tooltiprareness-1.0.4 (Latest 1.18.2)
